app:
    domain: localhost
    kind: development
    port: 8082
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYnMtbWFuYWdlbWVudC1zZXJ2aWNlIiwiaXNDb25maXJtRW1haWwiOnRydWUsInJvbGUiOiJzcnYiLCJpYXQiOjE2MDk2ODg2ODgsImF1ZCI6ImpvYnMtbWFuYWdlbWVudC1zZXJ2aWNlIiwiaXNzIjoiam9icy1tYW5hZ2VtZW50LXNlcnZpY2UiLCJzdWIiOiJqb2JzLW1hbmFnZW1lbnQtc2VydmljZSJ9.nezLhDuZd-mLsCtCp0aqxVcjN-u0cwvAIEAr__E4bv0

jwt:
    confirm_email:
        secret:
            jwt_secret: logpostemailconfirm
        options:
            expires_in: 14hr
            issuer: logpost
            audience: mailer
    private_route:
        secret:
            jwt_secret: logpostprivateroute
        options:
            expires_in: 30d
            issuer: logpost
            audience: logpost

shipper:
    api:
        base_url: http://localhost:8080
        prefix_route: /shipper

carrier:
    api:
        base_url: http://localhost:8081
        prefix_route: /carrier

db:
    required:
        isAuth: false
    mongo:
        protocal: mongodb
        username: null
        password: null
        host: localhost:27017
        database: logpost-stag
        options: ?authSource=admin
        collection: jobs
