app:
    domain: localhost
    kind: development
    port: 8082
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYnMtbWFuYWdlbWVudC1zZXJ2aWNlIiwiaWF0IjoxNjA0MDExMzYxLCJhdWQiOiJqb2JzLW1hbmFnZW1lbnQtc2VydmljZSIsImlzcyI6ImpvYnMtbWFuYWdlbWVudC1zZXJ2aWNlIiwic3ViIjoiam9icy1tYW5hZ2VtZW50LXNlcnZpY2UifQ.8-Y94inNy9N_xiWM4F_g161PgA0lq5H5XBMs77kYyRk

jwt:
    confirm_email:
        secret:
            jwt_secret: logpostemailconfirm
        options:
            expires_in: 14hr
            issuer: logpost
            audience: mailer
    private_route:
        secret:
            jwt_secret: logpostprivateroute
        options:
            expires_in: 30d
            issuer: logpost
            audience: logpost

shipper:
    api:
        base_url: https://shipper-management-service-logpost-stag-qjrfn6j7kq-as.a.run.app
        prefix_route: /shipper

carrier:
    api:
        base_url: https://carrier-management-service-logpost-stag-qjrfn6j7kq-as.a.run.app
        prefix_route: /carrier

db:
    required:
        isAuth: false
    mongo:
        protocal: mongodb
        username: null
        password: null
        host: localhost:27017
        database: logpost
        options: ?authSource=admin
        collection: jobs
