app:
    kind: production
    port: 8081

db:
    mongo:
        username: root
        password: root
        host: mongo
        port: 27017
        name: jobs_development
        auth: admin
        collection: jobs_account
